services:
  tic-mrf-scraper-local:
    build: .
    container_name: tic-mrf-scraper-local
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp:/app/temp
      - ./config.yaml:/app/config.yaml:ro
    command: ["python", "-m", "tic_mrf_scraper", "--config", "config.yaml"]
    deploy:
      resources:
        limits:
          memory: 24G
          cpus: '2.0'
        reservations:
          memory: 16G
          cpus: '1.0'
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3" 