cpt_whitelist:
- '99213'
- '99214'
- '72148'
- '73721'
- '70450'
- '0202U'
- '0240U'
- '0241U'
- '10005'
- '10006'
- '99500'
- '99502'
- '99503'
- '99505'
- '99506'
- '99509'
- '99510'
- '99511'
- '99512'
- '99600'
- '99602'
- '92521'
- '92522'
- '92523'
- '97162'
- '97163'
- '97164'
- '97165'
- '97166'
- '97167'
- '97168'
- 'G0008'
- 'G0009'
- 'G0010'
- 'M0201'
- 'T1019'
- 'T1020'
- 'T1021'
- 'T1022'
- 'G0151'
- 'G0152'
- 'G0153'
- 'G0156'
- 'G0299'
- 'G0300'
- 'S5125'
- 'S9131'
- 'A9272'
- '70030'
- '70100'
- '70110'
- '70120'
- '70130'
- '70134'
- '70140'
- '70150'
- '70160'
- '70190'
- '70200'
- '70210'
- '70220'
- '70240'
- '70250'
- '70260'
- '70328'
- '70330'
- '70336'
- '70360'
- '70370'
- '70450'
- '70460'
- '70470'
- '70480'
- '70481'
- '70482'
- '70486'
- '70487'
- '70488'
- '70490'
- '70491'
- '70492'
- '70540'
- '70542'
- '70543'
- '70544'
- '70551'
- '70552'
- '70553'
- '71010'
- '71020'
- '71021'
- '71022'
- '71023'
- '71030'
- '71034'
- '71035'
- '71046'
- '71100'
- '71101'
- '71110'
- '71111'
- '71120'
- '71130'
- '71250'
- '71260'
- '71270'
- '71275'
- '71550'
- '71551'
- '71552'
- '72020'
- '72040'
- '72050'
- '72052'
- '72070'
- '72072'
- '72074'
- '72080'
- '72082'
- '72083'
- '72084'
- '72100'
- '72110'
- '72114'
- '72120'
- '72125'
- '72126'
- '72127'
- '72128'
- '72129'
- '72130'
- '72131'
- '72132'
- '72133'
- '72141'
- '72142'
- '72146'
- '72147'
- '72148'
- '72149'
- '72156'
- '72157'
- '72158'
- '72170'
- '72190'
- '72192'
- '72193'
- '72194'
- '72195'
- '72196'
- '72197'
- '72200'
- '72202'
- '72220'
- '73000'
- '73010'
- '73020'
- '73030'
- '73040'
- '73050'
- '73060'
- '73070'
- '73080'
- '73090'
- '73092'
- '73100'
- '73110'
- '73120'
- '73130'
- '73140'
- '73200'
- '73201'
- '73202'
- '73218'
- '73219'
- '73220'
- '73221'
- '73222'
- '73223'
- '73501'
- '73502'
- '73503'
- '73521'
- '73522'
- '73523'
- '73525'
- '73551'
- '73552'
- '73560'
- '73561'
- '73562'
- '73564'
- '73565'
- '73580'
- '73590'
- '73592'
- '73600'
- '73610'
- '73620'
- '73630'
- '73650'
- '73660'
- '73700'
- '73701'
- '73702'
- '73718'
- '73719'
- '73720'
- '73721'
- '73722'
- '73723'
- '74000'
- '74010'
- '74020'
- '74150'
- '74160'
- '74170'
- '74176'
- '74177'
- '74178'
- '74181'
- '74182'
- '74183'
- '74220'
- '74240'
- '74241'
- '74245'
- '74246'
- '74247'
- '74249'
- '74250'
- '74251'
- '74270'
- '74280'
- '74400'
- '74410'
- '74740'
- '75561'
- '75571'
- '76010'
- '76080'
- '76376'
- '76377'
- '76536'
- '76604'
- '76642'
- '76700'
- '76705'
- '76770'
- '76775'
- '76830'
- '76856'
- '76857'
- '76870'
- '76882'
- '77002'
- '77003'
- '77012'
- '77072'
- '77073'
- '77074'
- '77075'
- '77076'
- '77077'
- '77080'
- '93971'
- '95870'
- '95885'
- '95886'
- '95887'
- '95909'
- '95910'
- '95911'
- '95912'
- '95913'
- '99202'
- '99203'
- '99204'
- '99214'
- '78306'
endpoints:
  #aetna_fl: file://C:\Users\chris\Downloads\2025-07-05_Aetna-Health-Inc----Florida_index.json.gz
  #anthem: https://antm-pt-prod-dataz-nogbd-nophi-us-east1.s3.amazonaws.com/anthem/2025-08-01_anthem_index.json.gz
  
  # bcbs_ks: https://mrf.secure.bcbsks.com/api/filedownloadhttptrigger?name=table-of-contents&ext=json
  bcbs_fl: https://d1hgtx7rrdl2cn.cloudfront.net/mrf/toc/FloridaBlue_Health-Insurance-Issuer_index.json
  #bcbs_il: https://app0004702110a5prdnc868.blob.core.windows.net/toc/2025-07-23_Blue-Cross-and-Blue-Shield-of-Illinois_index.json
  #bs_ca: file://C:\Users\ChristopherCato\Downloads\2025-08-01_Blue-Shield-of-California_index.json.gz
  cigna: https://d25kgz5rikkq4n.cloudfront.net/cost_transparency/mrf/table-of-contents/reporting_month=2025-08/2025-08-01_cigna-health-life-insurance-company_index.json?Expires=1757891470&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMjVrZ3o1cmlra3E0bi5jbG91ZGZyb250Lm5ldC9jb3N0X3RyYW5zcGFyZW5jeS9tcmYvdGFibGUtb2YtY29udGVudHMvcmVwb3J0aW5nX21vbnRoPTIwMjUtMDgvMjAyNS0wOC0wMV9jaWduYS1oZWFsdGgtbGlmZS1pbnN1cmFuY2UtY29tcGFueV9pbmRleC5qc29uIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzU3ODkxNDcwfX19XX0_&Signature=fg1XUcLNsxx7RYtuB88Qo5ainXP~yQaGXqvWocH1qCuWC8YW2s1nkFDfMmc3NlbLcfjG8X3g~p-v80yvx78wi9q0GmLxLbFEQueqfaBCvEV7i-ABQmVOl6XTZnNnO5HaHRRh9i6TbikcuUlQ4JmN65jZ8AhC0aFv5DAZmwaPZrpeKU81dSf254J8LZZq9q2-~VwIuIhlF6M9Yw6eODghYKrzBC2KluX5cNFYTpivXPNdckq9tIp-JsAZbJfP-1UetqOkszdOB9fFrEylwsFrHqHwV8803wbk8q2yapm-Y2lTfZzxDHtCJX2MGI6PaPKVRcy4oWCwcE3u2XUZtqdaaw__&Key-Pair-Id=K1NVBEPVH9LWJP
  #centene_fidelis: https://www.centene.com/content/dam/centene/Centene%20Corporate/json/DOCUMENT/2025-06-27_fidelis_index.json
  #bcbs_mi: https://bcbsm.sapphiremrfhub.com/tocs/current/blue_cross_blue_shield_of_michigan
  #bcbs_nc: https://mrfmftprod.bcbsnc.com/prod/etl/outbound/table-of-contents/non-aso/2025-07-29_blue-cross-and-blue-shield-of-north-carolina_index.json
logging:
  level: INFO
  output_file: /app/logs/etl_pipeline.log  # Updated for container path
  structured: true
output:
  local_directory: /app/data  # Updated for container path
  s3:
    bucket: commercial-rates
    prefix: tic-mrf-data/
    region: us-east-2
payer_endpoints:
  #aetna_fl: file://C:\Users\chris\Downloads\2025-07-05_Aetna-Health-Inc----Florida_index.json.gz
  #anthem: https://antm-pt-prod-dataz-nogbd-nophi-us-east1.s3.amazonaws.com/anthem/2025-08-01_anthem_index.json.gz
  cigna: https://d25kgz5rikkq4n.cloudfront.net/cost_transparency/mrf/table-of-contents/reporting_month=2025-08/2025-08-01_cigna-health-life-insurance-company_index.json?Expires=1757891470&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMjVrZ3o1cmlra3E0bi5jbG91ZGZyb250Lm5ldC9jb3N0X3RyYW5zcGFyZW5jeS9tcmYvdGFibGUtb2YtY29udGVudHMvcmVwb3J0aW5nX21vbnRoPTIwMjUtMDgvMjAyNS0wOC0wMV9jaWduYS1oZWFsdGgtbGlmZS1pbnN1cmFuY2UtY29tcGFueV9pbmRleC5qc29uIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzU3ODkxNDcwfX19XX0_&Signature=fg1XUcLNsxx7RYtuB88Qo5ainXP~yQaGXqvWocH1qCuWC8YW2s1nkFDfMmc3NlbLcfjG8X3g~p-v80yvx78wi9q0GmLxLbFEQueqfaBCvEV7i-ABQmVOl6XTZnNnO5HaHRRh9i6TbikcuUlQ4JmN65jZ8AhC0aFv5DAZmwaPZrpeKU81dSf254J8LZZq9q2-~VwIuIhlF6M9Yw6eODghYKrzBC2KluX5cNFYTpivXPNdckq9tIp-JsAZbJfP-1UetqOkszdOB9fFrEylwsFrHqHwV8803wbk8q2yapm-Y2lTfZzxDHtCJX2MGI6PaPKVRcy4oWCwcE3u2XUZtqdaaw__&Key-Pair-Id=K1NVBEPVH9LWJP
  #bs_ca: file://C:\Users\ChristopherCato\Downloads\2025-08-01_Blue-Shield-of-California_index.json.gz
  #bcbs_nc: https://mrfmftprod.bcbsnc.com/prod/etl/outbound/table-of-contents/non-aso/2025-07-29_blue-cross-and-blue-shield-of-north-carolina_index.json
  # bcbs_mi: https://bcbsm.sapphiremrfhub.com/tocs/current/blue_cross_blue_shield_of_michigan
  
  bcbs_fl: https://d1hgtx7rrdl2cn.cloudfront.net/mrf/toc/FloridaBlue_Health-Insurance-Issuer_index.json 
  #bcbs_il: https://app0004702110a5prdnc868.blob.core.windows.net/toc/2025-07-23_Blue-Cross-and-Blue-Shield-of-Illinois_index.json
  # bcbs_ks: https://mrf.secure.bcbsks.com/api/filedownloadhttptrigger?name=table-of-contents&ext=json
  #centene_fidelis: https://www.centene.com/content/dam/centene/Centene%20Corporate/json/DOCUMENT/2025-06-27_fidelis_index.json
processing:
  batch_size: 10000  # Reduced to force more frequent uploads
  file_types:
  - in_network_rates
  max_files_per_payer: null  # Process ALL files - no artificial limit
  max_records_per_file: null  # Process ALL records - no artificial limit
  safety_limit_records_per_file: 1000000  # Increased for comprehensive processing
  min_accuracy_score: 0.5  # Lowered to allow more records through
  min_completeness_pct: 30.0  # Lowered to allow more records through
  parallel_workers: 6  # Increased for 32GB RAM
  # Memory management settings for comprehensive processing
  memory_threshold_mb: 24576  # Increased to 24GB (75% of 32GB)
  max_processing_time_hours: 24  # Extended for comprehensive processing
  enable_memory_monitoring: true
  # Streaming and chunking settings
  enable_streaming: true
  chunk_size_mb: 100  # Increased chunk size for 32GB RAM
  enable_data_dumping: true  # Dump processed data to disk/S3 to free memory
  dump_interval_records: 100000  # Dump every 100K records for efficiency
versioning:
  processing_version: tic-etl-sample-v1.0
  retention_days: 7
  schema_version: v2.1.0-sample
